# Generated by Django 3.1.1 on 2020-10-05 08:22

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, verbose_name='School Name')),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('principal_name', models.CharField(max_length=100)),
                ('principal_phone_no', models.CharField(max_length=12, unique=True, validators=[registration.models.number_check])),
                ('no_of_students', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=12, validators=[registration.models.number_check])),
                ('upload_type', models.CharField(choices=[('Upload', 'Upload File'), ('URL', 'Spreadsheet URL')], default='URL', max_length=10)),
                ('url', models.URLField(blank=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to=registration.models.user_directory_path)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.school_info')),
            ],
        ),
    ]
