# Generated by Django 3.2 on 2021-05-11 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name*')),
                ('i_am', models.CharField(choices=[('Principal', 'Principal'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Staff', 'Staff')], default='Staff', max_length=10)),
                ('contact_number', models.CharField(max_length=12, validators=[registration.models.number_check], verbose_name='Contact Number*')),
                ('email', models.EmailField(max_length=50, verbose_name='Email*')),
                ('school_name', models.CharField(max_length=100, verbose_name='School Name*')),
                ('school_city', models.CharField(max_length=20, verbose_name='School City*')),
                ('awareness', models.CharField(blank=True, max_length=100, verbose_name='Where did you hear about us ?')),
                ('token', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='School_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, verbose_name='School Name')),
                ('school_code', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=12, unique=True, validators=[registration.models.number_check])),
                ('enrolments_to_CS', models.PositiveIntegerField()),
                ('no_of_teachers', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('contact_number', models.CharField(max_length=12, validators=[registration.models.number_check])),
                ('upload_type', models.CharField(choices=[('Upload', 'Upload File'), ('URL', 'Spreadsheet URL')], default='URL', max_length=10)),
                ('url', models.URLField(blank=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to=registration.models.user_directory_path)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.school_info')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.PositiveIntegerField(verbose_name='Class')),
                ('section', models.CharField(max_length=3)),
                ('teacher_email', models.EmailField(max_length=50)),
                ('contact_number', models.CharField(max_length=12, validators=[registration.models.number_check])),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.school_info')),
            ],
        ),
    ]
