# Generated by Django 3.2 on 2021-05-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_info',
            name='enrolments_to_CS',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='school_info',
            name='no_of_teachers',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='school_info',
            name='school_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
