# Generated by Django 3.1.1 on 2020-10-09 08:25

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('i_am', models.CharField(choices=[('Principal', 'Principal'), ('Teacher', 'Teacher'), ('Student', 'Student')], default='Principal', max_length=10)),
                ('contact_number', models.CharField(max_length=12, validators=[registration.models.number_check])),
                ('email', models.EmailField(max_length=50)),
                ('school_name', models.CharField(max_length=100, verbose_name='School Name')),
                ('school_city', models.CharField(max_length=20)),
                ('awareness', models.CharField(blank=True, max_length=100, verbose_name='Where did you hear about us ?')),
            ],
        ),
    ]
