# Generated by Django 3.1.1 on 2020-10-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_enquiry_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_data',
            name='i_am',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Staff', 'Staff')], default='Staff', max_length=10),
        ),
    ]
