# Generated by Django 3.2 on 2021-05-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210511_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_info',
            name='enrolments_to_CS',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_info',
            name='no_of_teachers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_info',
            name='school_name',
            field=models.CharField(max_length=100),
        ),
    ]
