# Generated by Django 3.1.1 on 2020-10-11 08:31

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20201009_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_info',
            old_name='principal_phone_no',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='school_info',
            old_name='no_of_students',
            new_name='enrolements_to_CS',
        ),
        migrations.RemoveField(
            model_name='school_info',
            name='city',
        ),
        migrations.RemoveField(
            model_name='school_info',
            name='principal_name',
        ),
        migrations.RemoveField(
            model_name='school_info',
            name='state',
        ),
        migrations.AddField(
            model_name='school_info',
            name='no_of_teachers',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_info',
            name='school_code',
            field=models.CharField(default='uhui6u', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry_data',
            name='contact_number',
            field=models.CharField(max_length=12, validators=[registration.models.number_check], verbose_name='Contact Number*'),
        ),
        migrations.AlterField(
            model_name='enquiry_data',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email*'),
        ),
        migrations.AlterField(
            model_name='enquiry_data',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name*'),
        ),
        migrations.AlterField(
            model_name='enquiry_data',
            name='school_city',
            field=models.CharField(max_length=20, verbose_name='School City*'),
        ),
        migrations.AlterField(
            model_name='enquiry_data',
            name='school_name',
            field=models.CharField(max_length=100, verbose_name='School Name*'),
        ),
        migrations.CreateModel(
            name='Class_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_class', models.PositiveIntegerField()),
                ('section', models.CharField(max_length=3)),
                ('teacher_email', models.EmailField(max_length=50)),
                ('contact_number', models.CharField(max_length=12, validators=[registration.models.number_check])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.school_info')),
            ],
        ),
    ]
