# Generated by Django 3.2 on 2021-05-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210511_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_info', models.BooleanField(default=False, verbose_name='School information (Principal)')),
                ('class_info', models.BooleanField(default=False, verbose_name='Class information (Teacher)')),
                ('data_consolidation', models.BooleanField(default=False, verbose_name='Data consolidation')),
                ('send_data', models.BooleanField(default=False, verbose_name='Send for profile creation')),
                ('receive_profiles', models.BooleanField(default=False, verbose_name='Received generated user profiles')),
                ('redistribution', models.BooleanField(default=False, verbose_name='Redistribution of profile credentials')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.school_info')),
            ],
        ),
    ]
