# Generated by Django 3.1.1 on 2020-10-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20201011_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_section',
            name='_class',
        ),
        migrations.AddField(
            model_name='class_section',
            name='class_no',
            field=models.PositiveIntegerField(default=7, verbose_name='Class'),
            preserve_default=False,
        ),
    ]
