# Generated by Django 3.1.1 on 2020-10-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20201011_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_info',
            old_name='phone_no',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='teacher_info',
            name='teacher_id',
        ),
    ]
