# Generated by Django 3.1.1 on 2020-10-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20201012_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_info',
            name='email',
            field=models.EmailField(default='initial@default.com', max_length=50),
            preserve_default=False,
        ),
    ]
