# Generated by Django 3.1.1 on 2020-10-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_teacher_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_info',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
