# Generated by Django 3.1.1 on 2020-10-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20201015_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_info',
            old_name='enrolements_to_CS',
            new_name='enrolments_to_CS',
        ),
    ]
