# Generated by Django 3.1.1 on 2020-10-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20201019_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_data',
            name='token',
            field=models.CharField(default='4wAiBLx1dLVLAD1To3QF', max_length=20, unique=True),
        ),
    ]
