# Generated by Django 3.1.1 on 2020-10-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_enquiry_data_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_data',
            name='token',
            field=models.CharField(default='m8t2jmoV6KR8HusQyTMr', max_length=20, unique=True),
        ),
    ]
