# Generated by Django 3.1.1 on 2020-10-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20201020_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_data',
            name='token',
            field=models.CharField(default='96chht63Q42I6RyC2q9c', max_length=20),
        ),
    ]
