# Generated by Django 3.1.1 on 2020-10-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20201025_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enquiry_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='school_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
