# Generated by Django 3.1.1 on 2020-10-25 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20201025_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_info',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
