# Generated by Django 3.0.3 on 2020-09-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='User_Detail',
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_first_app.Login'),
        ),
    ]
